### ISSUE TITLE
Introduce Test Group?

### ISSUE THREAD

**Issue by sdh21** [wy2249/Digo#61]
看到 additional_test，我感觉是不是给测试分几个group比较好？

1. Basic Parser/Syntax
2. Basic Semantic
3. Control Flow
4. Slice/String
5. Async/Async Remote
6. GC
7. I/O util

@lhxxh

没问题的话我改下bash脚本

**Comment by xiaomi388** [comment]
lgtm

**Comment by sdh21** [comment]
done
